name: CI
on: [push, pull_request]

jobs:
  build:
    name: MinGW
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingwVersion: [4.9, 5, 6, 7, 8]
        arch: [x86, x86_64]
        buildType: [Debug, Release]
        page: [1, 2]
        threads: [posix]
        include:
          - arch: "x86"
            exceptions: dwarf2
          - arch: "x86_64"
            exceptions: seh
    steps:
      - uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: install
        run: |
            set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
            pip.exe install conan --upgrade
            pip.exe install conan_package_tools bincrafters_package_tools
            conan user
      - name: run  
        env:
            CONAN_CURRENT_PAGE: ${{matrix.page}}
            CONAN_TOTAL_PAGES: 2
            CONAN_BUILD_TYPES: ${{matrix.buildType}}
            MINGW_CONFIGURATIONS: ${{matrix.mingwVersion}}@${{matrix.arch}}@${{matrix.exceptions}}@${{matrix.threads}}
            CONAN_OPTIONS:  "harfbuzz:with_glib=False"
        run: |
            python build.py